--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-20-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MKROOM_BOOKING_DATA
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_BOOKING_DATA" 
   (	"BOOKINGNUM" NUMBER(10,0), 
	"TODAYDATE" DATE DEFAULT sysdate, 
	"BRANCH_LOCATION" VARCHAR2(200 BYTE), 
	"QUESTNAME" VARCHAR2(100 BYTE), 
	"SELECTTIME" NUMBER(4,0), 
	"TEAMMEMBER" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_FILEINFO
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_FILEINFO" 
   (	"UUID" VARCHAR2(100 BYTE), 
	"UPLOADPATH" VARCHAR2(250 BYTE), 
	"FILENAME" VARCHAR2(100 BYTE), 
	"FILETYPE" CHAR(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_MEMBER
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_MEMBER" 
   (	"USERID" VARCHAR2(50 BYTE), 
	"USERPW" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"PHONENUMBER" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"REGDATE" TIMESTAMP (0) DEFAULT systimestamp(0), 
	"MODDATE" TIMESTAMP (0) DEFAULT systimestamp(0), 
	"DISCOUNTCOUPON" NUMBER(10,0), 
	"QUESTPOINT" NUMBER(10,0), 
	"DROPFLG" CHAR(1 BYTE) DEFAULT '0', 
	"ENABLED" CHAR(1 BYTE) DEFAULT '1'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_MEMBER_AUTHORITIES
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_MEMBER_AUTHORITIES" 
   (	"USERID" VARCHAR2(50 BYTE), 
	"AUTHORITY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_NOTICE_EVENT
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_NOTICE_EVENT" 
   (	"BNO" NUMBER(10,0), 
	"BTITLE" VARCHAR2(200 BYTE), 
	"BCONTENT" VARCHAR2(4000 BYTE), 
	"BWRITER" VARCHAR2(100 BYTE), 
	"BREGDATE" DATE DEFAULT sysdate, 
	"BMODDATE" TIMESTAMP (0) DEFAULT systimestamp(0), 
	"BVIEWCNT" NUMBER(20,0), 
	"BREPLYCNT" NUMBER(20,0), 
	"BDELFLAG" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_NOTICE_EVENT_ATTACHFILES
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_NOTICE_EVENT_ATTACHFILES" 
   (	"UUID" VARCHAR2(100 BYTE), 
	"BNO" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_NOTICE_EVENT_REPLY
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_NOTICE_EVENT_REPLY" 
   (	"RNO" NUMBER(10,0), 
	"BNO" NUMBER(10,0), 
	"RCONTENT" VARCHAR2(4000 BYTE), 
	"RWRITER" VARCHAR2(100 BYTE), 
	"RREGDATE" DATE DEFAULT sysdate, 
	"RMODDATE" TIMESTAMP (0) DEFAULT systimestamp(0), 
	"PRNO" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_PERSISTENT_LOGINS
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_PERSISTENT_LOGINS" 
   (	"USERNAME" VARCHAR2(64 BYTE), 
	"SERIES" VARCHAR2(64 BYTE), 
	"TOKEN" VARCHAR2(64 BYTE), 
	"LAST_USED" TIMESTAMP (0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_QNA
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_QNA" 
   (	"BNO" NUMBER(10,0), 
	"BTITLE" VARCHAR2(200 BYTE), 
	"BCONTENT" VARCHAR2(4000 BYTE), 
	"BWRITER" VARCHAR2(100 BYTE), 
	"BREGDATE" DATE DEFAULT sysdate, 
	"BVIEWCNT" NUMBER(20,0), 
	"BREPLYCNT" NUMBER(20,0), 
	"BDELFLAG" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_QNA_ATTACHFILES
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_QNA_ATTACHFILES" 
   (	"UUID" VARCHAR2(100 BYTE), 
	"BNO" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_QNA_REPLY
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_QNA_REPLY" 
   (	"RNO" NUMBER(10,0), 
	"BNO" NUMBER(10,0), 
	"RCONTENT" VARCHAR2(4000 BYTE), 
	"RWRITER" VARCHAR2(100 BYTE), 
	"RREGDATE" DATE DEFAULT sysdate, 
	"RMODDATE" TIMESTAMP (0) DEFAULT systimestamp(0), 
	"REPLYORNOT" NUMBER(1,0), 
	"PRNO" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_QUEST
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_QUEST" 
   (	"QUESTNAME" VARCHAR2(100 BYTE), 
	"MAXPLAYERNUM" NUMBER(2,0), 
	"GENRE" CHAR(2 BYTE), 
	"DIFFICULTY" NUMBER(2,0), 
	"BRANCH_LOCATION" VARCHAR2(200 BYTE), 
	"UUID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
REM INSERTING into MKROOM.MKROOM_BOOKING_DATA
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_FILEINFO
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_MEMBER
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_MEMBER_AUTHORITIES
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_NOTICE_EVENT
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_NOTICE_EVENT_ATTACHFILES
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_NOTICE_EVENT_REPLY
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_PERSISTENT_LOGINS
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_QNA
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_QNA_ATTACHFILES
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_QNA_REPLY
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_QUEST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_BOOKING_DATA
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_BOOKING_DATA" ON "MKROOM"."MKROOM_BOOKING_DATA" ("BOOKINGNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_FILEINFO
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_FILEINFO" ON "MKROOM"."MKROOM_FILEINFO" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_MEMBER" ON "MKROOM"."MKROOM_MEMBER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_MEMBER_AUTHORITIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_MEMBER_AUTHORITIES" ON "MKROOM"."MKROOM_MEMBER_AUTHORITIES" ("USERID", "AUTHORITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_NOTICE_EVENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_NOTICE_EVENT" ON "MKROOM"."MKROOM_NOTICE_EVENT" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_NOTICE_EVENT_ATTACHFILES
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_NOTICE_EVENT_ATTACHFILES" ON "MKROOM"."MKROOM_NOTICE_EVENT_ATTACHFILES" ("BNO", "UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_NOTICE_EVENT_REPLY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_NOTICE_EVENT_REPLY" ON "MKROOM"."MKROOM_NOTICE_EVENT_REPLY" ("BNO", "RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_PERSISTENT_LOGINS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_PERSISTENT_LOGINS" ON "MKROOM"."MKROOM_PERSISTENT_LOGINS" ("SERIES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_QNA
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_QNA" ON "MKROOM"."MKROOM_QNA" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_QNA_ATTACHFILES
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_QNA_ATTACHFILES" ON "MKROOM"."MKROOM_QNA_ATTACHFILES" ("BNO", "UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_QNA_REPLY
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_QNA_REPLY" ON "MKROOM"."MKROOM_QNA_REPLY" ("BNO", "RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_QUEST
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_QUEST" ON "MKROOM"."MKROOM_QUEST" ("QUESTNAME", "BRANCH_LOCATION", "DIFFICULTY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MKROOM_NOTICE_EVENT_REPLY
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT_REPLY" MODIFY ("RCONTENT" CONSTRAINT "NN_RCONTENT_MKREPLY" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT_REPLY" MODIFY ("RWRITER" CONSTRAINT "NN_RWRITER_MKREPLY" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT_REPLY" ADD CONSTRAINT "PK_MKROOM_NOTICE_EVENT_REPLY" PRIMARY KEY ("BNO", "RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_QNA_ATTACHFILES
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_QNA_ATTACHFILES" ADD CONSTRAINT "PK_MKROOM_QNA_ATTACHFILES" PRIMARY KEY ("BNO", "UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_FILEINFO
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_FILEINFO" MODIFY ("UPLOADPATH" CONSTRAINT "NN_UPLOADPATH_MKFILEINFO" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_FILEINFO" MODIFY ("FILENAME" CONSTRAINT "NN_FILENAME_MKFILEINFO" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_FILEINFO" MODIFY ("FILETYPE" CONSTRAINT "NN_FILETYPE_MKFILEINFO" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_FILEINFO" ADD CONSTRAINT "PK_MKROOM_FILEINFO" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_QNA
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_QNA" MODIFY ("BTITLE" CONSTRAINT "NN_BTITLE_MKQNA" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_QNA" MODIFY ("BCONTENT" CONSTRAINT "NN_BCONTENT_MKQNA" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_QNA" MODIFY ("BWRITER" CONSTRAINT "NN_BWRITER_MKQNA" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_QNA" ADD CONSTRAINT "PK_MKROOM_QNA" PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_QUEST
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_QUEST" ADD CONSTRAINT "PK_MKROOM_QUEST" PRIMARY KEY ("QUESTNAME", "BRANCH_LOCATION", "DIFFICULTY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_MEMBER
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_MEMBER" MODIFY ("USERPW" CONSTRAINT "NN_USERPW_MKMEMBER" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_MEMBER" MODIFY ("USERNAME" CONSTRAINT "NN_USERNAME_MKMEMBER" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_MEMBER" MODIFY ("PHONENUMBER" CONSTRAINT "NN_PHONENUMBER_MKMEMBER" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_MEMBER" ADD CONSTRAINT "PK_MKROOM_MEMBER" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_PERSISTENT_LOGINS
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_PERSISTENT_LOGINS" MODIFY ("USERNAME" CONSTRAINT "NN_USERNAME_MKPERSISTENT_LOGINS" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_PERSISTENT_LOGINS" MODIFY ("TOKEN" CONSTRAINT "NN_TOKEN_MKPERSISTENT_LOGINS" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_PERSISTENT_LOGINS" MODIFY ("LAST_USED" CONSTRAINT "NN_LAST_USED_MKPERSISTENT_LOGINS" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_PERSISTENT_LOGINS" ADD CONSTRAINT "PK_MKROOM_PERSISTENT_LOGINS" PRIMARY KEY ("SERIES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_NOTICE_EVENT
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT" MODIFY ("BTITLE" CONSTRAINT "NN_BTITLE_MKBOARD" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT" MODIFY ("BCONTENT" CONSTRAINT "NN_BCONTENT_MKBOARD" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT" MODIFY ("BWRITER" CONSTRAINT "NN_BWRITER_MKBOARD" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT" ADD CONSTRAINT "PK_MKROOM_NOTICE_EVENT" PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_MEMBER_AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_MEMBER_AUTHORITIES" ADD CONSTRAINT "PK_MKROOM_MEMBER_AUTHORITIES" PRIMARY KEY ("USERID", "AUTHORITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_BOOKING_DATA
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_BOOKING_DATA" MODIFY ("BRANCH_LOCATION" CONSTRAINT "NN_BRANCH_LOCATION_MKBOOKING" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_BOOKING_DATA" ADD CONSTRAINT "PK_MKROOM_BOOKING_DATA" PRIMARY KEY ("BOOKINGNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_QNA_REPLY
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_QNA_REPLY" MODIFY ("RCONTENT" CONSTRAINT "NN_RCONTENT_MKQNAREPLY" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_QNA_REPLY" MODIFY ("RWRITER" CONSTRAINT "NN_RWRITER_MKQNAREPLY" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_QNA_REPLY" ADD CONSTRAINT "PK_MKROOM_QNA_REPLY" PRIMARY KEY ("BNO", "RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_NOTICE_EVENT_ATTACHFILES
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT_ATTACHFILES" ADD CONSTRAINT "PK_MKROOM_NOTICE_EVENT_ATTACHFILES" PRIMARY KEY ("BNO", "UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MKROOM_MEMBER_AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_MEMBER_AUTHORITIES" ADD CONSTRAINT "FK_USERID_ATTACHFILES" FOREIGN KEY ("USERID")
	  REFERENCES "MKROOM"."MKROOM_MEMBER" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MKROOM_NOTICE_EVENT_ATTACHFILES
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT_ATTACHFILES" ADD CONSTRAINT "FK_BNO_ATTACHFILES" FOREIGN KEY ("BNO")
	  REFERENCES "MKROOM"."MKROOM_NOTICE_EVENT" ("BNO") ENABLE;
  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT_ATTACHFILES" ADD CONSTRAINT "FK_UUID_ATTACHFILES" FOREIGN KEY ("UUID")
	  REFERENCES "MKROOM"."MKROOM_FILEINFO" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MKROOM_NOTICE_EVENT_REPLY
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT_REPLY" ADD CONSTRAINT "FK_BNO_PRNO_REPLY" FOREIGN KEY ("BNO", "PRNO")
	  REFERENCES "MKROOM"."MKROOM_NOTICE_EVENT_REPLY" ("BNO", "RNO") ENABLE;
  ALTER TABLE "MKROOM"."MKROOM_NOTICE_EVENT_REPLY" ADD CONSTRAINT "FK_BNO_REPLY" FOREIGN KEY ("BNO")
	  REFERENCES "MKROOM"."MKROOM_NOTICE_EVENT" ("BNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MKROOM_QNA_ATTACHFILES
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_QNA_ATTACHFILES" ADD CONSTRAINT "FK_BNO_QNA_ATTACHFILES" FOREIGN KEY ("BNO")
	  REFERENCES "MKROOM"."MKROOM_QNA" ("BNO") ENABLE;
  ALTER TABLE "MKROOM"."MKROOM_QNA_ATTACHFILES" ADD CONSTRAINT "FK_UUID_QNA_ATTACHFILES" FOREIGN KEY ("UUID")
	  REFERENCES "MKROOM"."MKROOM_FILEINFO" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MKROOM_QNA_REPLY
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_QNA_REPLY" ADD CONSTRAINT "FK_BNO_PRNO_QNA_REPLY" FOREIGN KEY ("BNO", "PRNO")
	  REFERENCES "MKROOM"."MKROOM_QNA_REPLY" ("BNO", "RNO") ENABLE;
  ALTER TABLE "MKROOM"."MKROOM_QNA_REPLY" ADD CONSTRAINT "FK_BNO_QNA_REPLY" FOREIGN KEY ("BNO")
	  REFERENCES "MKROOM"."MKROOM_QNA" ("BNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MKROOM_QUEST
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_QUEST" ADD CONSTRAINT "FK_UUID_MKROOM_QUEST" FOREIGN KEY ("UUID")
	  REFERENCES "MKROOM"."MKROOM_FILEINFO" ("UUID") ENABLE;
