--------------------------------------------------------
--  파일이 생성됨 - 월요일-12월-19-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MKROOM_ATTACHFILES
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_ATTACHFILES" 
   (	"UUID" VARCHAR2(100 BYTE), 
	"MKROOM_BNO" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_BOARD
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_BOARD" 
   (	"MKROOM_BNO" NUMBER(10,0), 
	"MKROOM_BTITLE" VARCHAR2(200 BYTE), 
	"MKROOM_BCONTENT" VARCHAR2(4000 BYTE), 
	"MKROOM_BWRITER" VARCHAR2(100 BYTE), 
	"MKROOM_BREGDATE" DATE DEFAULT sysdate, 
	"MKROOM_BMODDATE" TIMESTAMP (6) DEFAULT systimestamp(0), 
	"MKROOM_BVIEWCNT" NUMBER(20,0), 
	"MKROOM_BREPLYCNT" NUMBER(20,0), 
	"MKROOM_BDELFLAG" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_FILEINFO
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_FILEINFO" 
   (	"UUID" VARCHAR2(100 BYTE), 
	"UPLOADPATH" VARCHAR2(250 BYTE), 
	"FILENAME" VARCHAR2(100 BYTE), 
	"FILETYPE" CHAR(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_MEMBER
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_MEMBER" 
   (	"USERID" VARCHAR2(50 BYTE), 
	"USERPW" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"MREGDATE" TIMESTAMP (0) DEFAULT systimestamp(0), 
	"MODDATE" TIMESTAMP (0) DEFAULT systimestamp(0), 
	"MDROPFLG" CHAR(1 BYTE) DEFAULT '0', 
	"ENABLED" CHAR(1 BYTE) DEFAULT '1'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_MEMBER_AUTHORITIES
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_MEMBER_AUTHORITIES" 
   (	"USERID" VARCHAR2(50 BYTE), 
	"AUTHORITY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_PERSISTENT_LOGINS
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_PERSISTENT_LOGINS" 
   (	"USERNAME" VARCHAR2(64 BYTE), 
	"SERIES" VARCHAR2(64 BYTE), 
	"TOKEN" VARCHAR2(64 BYTE), 
	"LAST_USED" TIMESTAMP (0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
--------------------------------------------------------
--  DDL for Table MKROOM_REPLY
--------------------------------------------------------

  CREATE TABLE "MKROOM"."MKROOM_REPLY" 
   (	"MKROOM_RNO" NUMBER(10,0), 
	"MKROOM_BNO" NUMBER(10,0), 
	"MKROOM_RCONTENT" VARCHAR2(4000 BYTE), 
	"MKROOM_RWRITER" VARCHAR2(100 BYTE), 
	"MKROOM_RREGDATE" DATE DEFAULT sysdate, 
	"MKROOM_RMODDATE" TIMESTAMP (6) DEFAULT systimestamp(0), 
	"MKROOM_PRNO" NUMBER(20,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "MKROOM_SPACE" ;
REM INSERTING into MKROOM.MKROOM_ATTACHFILES
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_BOARD
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_FILEINFO
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_MEMBER
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_MEMBER_AUTHORITIES
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_PERSISTENT_LOGINS
SET DEFINE OFF;
REM INSERTING into MKROOM.MKROOM_REPLY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_FILEINFO_MKROOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_FILEINFO_MKROOM" ON "MKROOM"."MKROOM_FILEINFO" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_ATTACHFILES
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_ATTACHFILES" ON "MKROOM"."MKROOM_ATTACHFILES" ("UUID", "MKROOM_BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_REPLY_MKROOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_REPLY_MKROOM" ON "MKROOM"."MKROOM_REPLY" ("MKROOM_BNO", "MKROOM_RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOARD_MKROOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_BOARD_MKROOM" ON "MKROOM"."MKROOM_BOARD" ("MKROOM_BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_MEMBER" ON "MKROOM"."MKROOM_MEMBER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_MEMBER_AUTHORITIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_MEMBER_AUTHORITIES" ON "MKROOM"."MKROOM_MEMBER_AUTHORITIES" ("USERID", "AUTHORITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MKROOM_PERSISTENT_LOGINS
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKROOM"."PK_MKROOM_PERSISTENT_LOGINS" ON "MKROOM"."MKROOM_PERSISTENT_LOGINS" ("SERIES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MKROOM_PERSISTENT_LOGINS
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_PERSISTENT_LOGINS" MODIFY ("USERNAME" CONSTRAINT "NN_USERNAME_MKPERSISTENT_LOGINS" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_PERSISTENT_LOGINS" MODIFY ("TOKEN" CONSTRAINT "NN_TOKEN_MKPERSISTENT_LOGINS" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_PERSISTENT_LOGINS" MODIFY ("LAST_USED" CONSTRAINT "NN_LAST_USED_MKPERSISTENT_LOGINS" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_PERSISTENT_LOGINS" ADD CONSTRAINT "PK_MKROOM_PERSISTENT_LOGINS" PRIMARY KEY ("SERIES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_MEMBER_AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_MEMBER_AUTHORITIES" ADD CONSTRAINT "PK_MKROOM_MEMBER_AUTHORITIES" PRIMARY KEY ("USERID", "AUTHORITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_REPLY
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_REPLY" MODIFY ("MKROOM_RCONTENT" CONSTRAINT "NN_RCONTENT_MKREPLY" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_REPLY" MODIFY ("MKROOM_RWRITER" CONSTRAINT "NN_RWRITER_MKREPLY" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_REPLY" ADD CONSTRAINT "PK_REPLY_MKROOM" PRIMARY KEY ("MKROOM_BNO", "MKROOM_RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_BOARD
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_BOARD" MODIFY ("MKROOM_BTITLE" CONSTRAINT "NN_BTITLE_MKBOARD" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_BOARD" MODIFY ("MKROOM_BCONTENT" CONSTRAINT "NN_BCONTENT_MKBOARD" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_BOARD" MODIFY ("MKROOM_BWRITER" CONSTRAINT "NN_BWRITER_MKBOARD" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_BOARD" ADD CONSTRAINT "PK_BOARD_MKROOM" PRIMARY KEY ("MKROOM_BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_FILEINFO
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_FILEINFO" MODIFY ("FILENAME" CONSTRAINT "NN_FILENAME_MKFILEINFO" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_FILEINFO" MODIFY ("FILETYPE" CONSTRAINT "NN_FILETYPE_MKFILEINFO" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_FILEINFO" ADD CONSTRAINT "PK_FILEINFO_MKROOM" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_ATTACHFILES
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_ATTACHFILES" ADD CONSTRAINT "PK_MKROOM_ATTACHFILES" PRIMARY KEY ("UUID", "MKROOM_BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MKROOM_MEMBER
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_MEMBER" MODIFY ("USERPW" CONSTRAINT "NN_USERPW_MKMEMBER" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_MEMBER" MODIFY ("USERNAME" CONSTRAINT "NN_USERNAME_MKMEMBER" NOT NULL ENABLE);
  ALTER TABLE "MKROOM"."MKROOM_MEMBER" ADD CONSTRAINT "PK_MKROOM_MEMBER" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MKROOM_ATTACHFILES
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_ATTACHFILES" ADD CONSTRAINT "FK_BNO_ATTACHFILES" FOREIGN KEY ("MKROOM_BNO")
	  REFERENCES "MKROOM"."MKROOM_BOARD" ("MKROOM_BNO") ENABLE;
  ALTER TABLE "MKROOM"."MKROOM_ATTACHFILES" ADD CONSTRAINT "FK_UUID_ATTACHFILES" FOREIGN KEY ("UUID")
	  REFERENCES "MKROOM"."MKROOM_FILEINFO" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MKROOM_MEMBER_AUTHORITIES
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_MEMBER_AUTHORITIES" ADD CONSTRAINT "FK_USERID_ATTACHFILES" FOREIGN KEY ("USERID")
	  REFERENCES "MKROOM"."MKROOM_MEMBER" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MKROOM_REPLY
--------------------------------------------------------

  ALTER TABLE "MKROOM"."MKROOM_REPLY" ADD CONSTRAINT "FK_BNO_REPLY" FOREIGN KEY ("MKROOM_BNO")
	  REFERENCES "MKROOM"."MKROOM_BOARD" ("MKROOM_BNO") ENABLE;
  ALTER TABLE "MKROOM"."MKROOM_REPLY" ADD CONSTRAINT "FK_BNO_PRNO_REPLY" FOREIGN KEY ("MKROOM_BNO", "MKROOM_PRNO")
	  REFERENCES "MKROOM"."MKROOM_REPLY" ("MKROOM_BNO", "MKROOM_RNO") ENABLE;
